---
title: "TC_Graphs"
author: "Aubrey Keirnan"
date: "2023-09-19"
output: html_document
editor_options:
  chunk_output_type: console
---

---
```{r}
load(file = "../Data/Processed/TeleCere_data_processed.rda")
#load(file="../Data/Processed/Linear_models.rda")
#load(file="../Data/Processed/LM_Coefficients.rda")
#load(file="../Data/Processed/Bird_silhouettes.rda")
load(file="../Data/Processed/phylo_confidence_intervals.rda")
load(file="../Data/Processed/phylo_prediction_intervals.rda")



library(RColorBrewer)
library(plyr)
#install.packages("viridisLite")
library(viridisLite)
#library(devtools)
#install_github("JeroenSmaers/evomap" )
library (evomap)
library(png)
library(jpeg)
library(plotrix)
library(vioplot)


library(htmltools)
library(ape)         # CRAN v5.5 
library(nlme)        # CRAN v3.1-153
library(geiger)      # CRAN v2.0.7
library(rstudioapi)  # CRAN v0.13
library(devtools)    # CRAN v2.4.3
library(phytools)    # CRAN v0.7-90
library(performance) # CRAN v0.8.0
library(TreeTools)
library(phytools)
library(car)


```

#Cosmetics
```{r}

colsOrder=c(magma(25,begin = 0, end = 1, direction = -1))
names(colsOrder)<- levels (as.factor(Data_raw$order))

colsOrderBG=c(viridis(25,begin = 0, end = 1, direction = 1))
names(colsOrderBG)<- levels (as.factor(Data_raw$order))

pchOrder=c(25, 22, 23, 24, 21, 3, 4, 8, 9, 11, 25, 22, 23, 24, 21, 3, 4, 8, 9, 11, 25, 22, 23, 24, 21)
names(pchOrder)<- levels (as.factor(Data_raw$order))



Phylo_Data_Cere$Tree_label_name <- rownames(Phylo_Data_Cere)
Phylo_Data_Telen$Tree_label_name <- rownames(Phylo_Data_Telen)
a <- rep(1, length(Data_raw$endoSA))

```
####FIGURE 2
#LM direct comparisons
```{r}
pdf("../Figures/Figure2.pdf", height = 10, width = 10)
par(mar=c(5, 5, 3, 1), mfrow=c(2,2))


x <- log(Data_raw$brVOL_cere)
y <- log(Data_raw$endoSA)

# generate linear model
lm.mod <- lm(y ~ x)

# generate equidistant x values for lines
newx = seq(min(x),max(x),by = 0.05)

conf_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'confidence', level=0.95)
pred_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'prediction', level=0.95)

plot(log(Data_raw$endoSA) ~ log(Data_raw$brVOL_cere), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order], cex=1, ylab="Log Surface Area (mm²)", xlab="Log Brain Volume (mm³)", cex.axis=1.5, cex.lab=1.5);

polygon(c(newx, rev(newx)), c(pred_interval[,2], rev(pred_interval[,3])), col = grey (0.9), border = NA )
polygon(c(newx, rev(newx)), c(conf_interval[,2], rev(conf_interval[,3])), col = grey (0.5), border = NA )

abline(lm.mod, col="black", lwd=2);

par(new=TRUE)

plot(log(Data_raw$endoSA) ~ log(Data_raw$brVOL_cere), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order], cex=1, ylab="Log Surface Area (mm²)", xlab="Log Brain Volume (mm³)", cex.axis=1.5, cex.lab=1.5);




legend('topleft', legend = "(a) Whole Endocast", cex = 2, bty = 'n')



x <- log(Phylo_Data_Telen$telenVOL)
y <- log(Phylo_Data_Telen$telenSA)

# generate linear model
lm.mod <- lm(y ~ x)

# generate equidistant x values for lines
newx = seq(min(x),max(x),by = 0.05)

conf_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'confidence', level=0.95)
pred_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'prediction', level=0.95)

# plot initial values with regression line and confidence intervals
#tele SA on VOL
plot(log(Data_raw$telenSA) ~ log(Data_raw$telenVOL), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order], cex=1, ylab="Log Surface Area (mm²)", xlab="Log Volume (mm³)", cex.axis=1.5, cex.lab=1.5);

polygon(c(newx, rev(newx)), c(pred_interval[,2], rev(pred_interval[,3])), col = grey (0.9), border = NA )
polygon(c(newx, rev(newx)), c(conf_interval[,2], rev(conf_interval[,3])), col = grey (0.5), border = NA )

abline(lm.mod, col="black", lwd=2);

par(new=TRUE)


plot(log(Data_raw$telenSA) ~ log(Data_raw$telenVOL), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order], cex=1, ylab="Log Surface Area (mm²)", xlab="Log Volume (mm³)", cex.axis=1.5, cex.lab=1.5);
#lines(newx, yupper, col="grey", lty=2, lwd=3);
#lines(newx, ylower, col="grey", lty=2, lwd=3);
#text(log(Data_raw$telenVOL), log(Data_raw$telenSA)-0.02, labels=(rownames(Data_raw)), cex=0.7);

legend('topleft', legend = "(b) Telencephalon", cex = 2, bty = 'n')






x <- log(Phylo_Data_Cere$cereVOL)
y <- log(Phylo_Data_Cere$cereSA)

# generate linear model
lm.mod <- lm(y ~ x)

# generate equidistant x values for lines
newx = seq(min(x),max(x),by = 0.05)

conf_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'confidence', level=0.95)
pred_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'prediction', level=0.95)

# plot initial values with regression line and confidence intervals
plot(log(Data_raw$cereSA) ~ log(Data_raw$cereVOL), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order], cex=1, ylab="Log Surface Area (mm²)", xlab="Log Volume (mm³)", cex.axis=1.5, cex.lab=1.5);

polygon(c(newx, rev(newx)), c(pred_interval[,2], rev(pred_interval[,3])), col = grey (0.9), border = NA )
polygon(c(newx, rev(newx)), c(conf_interval[,2], rev(conf_interval[,3])), col = grey (0.5), border = NA )

abline(lm.mod, col="black", lwd=2);

par(new=TRUE)

plot(log(Data_raw$cereSA) ~ log(Data_raw$cereVOL), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order], cex=1, ylab="Log Surface Area (mm²)", xlab="Log Volume (mm³)", cex.axis=1.5, cex.lab=1.5);

legend('topleft', legend = "(c) Cerebellum", cex = 2, bty = 'n')



# Create a blank plot with no data and no box so that the legend will sit in the right spot outside of the graphs
plot(NA, xlim = c(0, 1), ylim = c(0, 1), type = "n", xlab = "", ylab = "", main = "", axes = FALSE)
legend("topleft",inset=c(-0.15,0), levels(as.factor(Data_raw$order)),  pt.bg=colsOrderBG, col=colsOrder, pch=pchOrder, cex=1.5, bty="n",xpd = TRUE, ncol=2)

# Close the PDF device
dev.off()

```


###FIGURE 3

#Scaling - Region against remainder
```{r}
pdf("../Figures/Figure3.pdf", height = 15, width = 12)
par(mar=c(5, 5, 3, 3),mfrow=c(3,2))


##TelenSA on Endo Remainder
x <- log(Data_raw$enminustelenSA)
y <- log(Data_raw$telenSA)

# generate linear model
lm.mod <- lm(y ~ x)

# generate equidistant x values for lines
newx = seq(min(x),max(x),by = 0.05)

conf_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'confidence', level=0.95)
pred_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'prediction', level=0.95)


plot(log(Data_raw$telenSA) ~ log(Data_raw$enminustelenSA), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order],  cex=2, ylab="Telencephalon from Endocast", xlab="Endocast Remainder ", cex.main=3, cex.axis=1.8, cex.lab=1.8);

#Here we make the  CI polygon. To make that appear behind the plot, I have to repeat the plot command
polygon(c(TeleEndo_gm_CI$CI.plot$X, rev (TeleEndo_gm_CI$CI.plot$X)), c(TeleEndo_gm_CI$CI.plot$Lower2.5, rev(TeleEndo_gm_CI$CI.plot$Upper2.5)), col = "lightpink", border = NA )

polygon(c(newx, rev(newx)), c(pred_interval[,2], rev(pred_interval[,3])), col = grey (0.9), border = NA )
polygon(c(newx, rev(newx)), c(conf_interval[,2], rev(conf_interval[,3])), col = grey (0.5), border = NA )

abline(lm.mod, col="black", lwd=2);

 #I am here using the abline from the evomap code, but the pgls with brownian settings results in teh same line
abline (TeleEndo_gm_CI$model[1,1], TeleEndo_gm_CI$model[2,1], col="red", lwd=2, lty=5)


par(new=TRUE)

plot(log(Data_raw$telenSA) ~ log(Data_raw$enminustelenSA), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order],  cex=2, ylab="Telencephalon from Endocast", xlab="Endocast Remainder ", cex.main=3, cex.axis=1.8, cex.lab=1.8);
#text(log(Data_raw$enminustelenSA), log(Data_raw$telenSA)-0.02, labels=(rownames(Data_raw)), cex=0.3);


legend('topleft', legend = "(a) Log Surface Area (mm²)", cex = 2, bty = 'n')

model <- ((gls( log(telenSA) ~ log(enminustelenSA), correlation = corBrownian(1,consensus_tree_telen, form=~Tree_label_name), data=Phylo_Data_Telen)));
# 
# 
modsum = summary(model)

pgls.slope=coef(modsum)[2]
lm.slope=coef(lm.mod)[2]

rp = vector('expression',2)
 
rp[1] = substitute(expression(LM_Slope == MYVALUE), list(MYVALUE = format(lm.slope,dig=3)))[2]
rp[2] = substitute(expression(PGLS_Slope == MYVALUE), list(MYVALUE = format(pgls.slope,dig=3)))[2]

legend('bottomright', legend = rp, bty = 'n', cex=1.5)



##TelenVOL on Brain remainder
x <- log(Phylo_Data_Telen$brminustelenVOL)
y <- log(Phylo_Data_Telen$telenVOL)

# generate linear model
lm.mod <- lm(y ~ x)

# generate equidistant x values for lines
newx = seq(min(x),max(x),by = 0.05)

conf_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'confidence', level=0.95)
pred_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'prediction', level=0.95)



plot(log(Data_raw$telenVOL) ~ log(Data_raw$brminustelenVOL), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order],  cex=2, ylab="Telencephalon from Brain", xlab="Brain Remainder", cex.main=3, cex.axis=1.8, cex.lab=1.8);

#Here we make the  CI polygon. To make that appear behind the plot, I have to repeat the plot command
polygon(c(TeleBrain_gm_CI$CI.plot$X, rev (TeleBrain_gm_CI$CI.plot$X)), c(TeleBrain_gm_CI$CI.plot$Lower2.5, rev(TeleBrain_gm_CI$CI.plot$Upper2.5)), col = "lightpink", border = NA )

polygon(c(newx, rev(newx)), c(pred_interval[,2], rev(pred_interval[,3])), col = grey (0.9), border = NA )
polygon(c(newx, rev(newx)), c(conf_interval[,2], rev(conf_interval[,3])), col = grey (0.5), border = NA )

abline(lm.mod, col="black", lwd=2);

 #I am here using the abline from the evomap code, but the pgls with brownian settings results in teh same line
abline (TeleBrain_gm_CI$model[1,1], TeleBrain_gm_CI$model[2,1], col="red", lwd=2, lty=5)


par(new=TRUE)

plot(log(Data_raw$telenVOL) ~ log(Data_raw$brminustelenVOL), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order],  cex=2, ylab="Telencephalon from Brain", xlab="Brain Remainder", cex.main=3, cex.axis=1.8, cex.lab=1.8);


legend('topleft', legend = "(b) Log Volume (mm³)", cex = 2, bty = 'n')

model <- ((gls( log(telenVOL) ~ log(brminustelenVOL), correlation = corBrownian(1,consensus_tree_telen, form=~Tree_label_name), data=Phylo_Data_Telen)));
# 
# 
modsum = summary(model)

pgls.slope=coef(modsum)[2]
lm.slope=coef(lm.mod)[2]

rp = vector('expression',2)
 
rp[1] = substitute(expression(LM_Slope == MYVALUE), list(MYVALUE = format(lm.slope,dig=3)))[2]
rp[2] = substitute(expression(PGLS_Slope == MYVALUE), list(MYVALUE = format(pgls.slope,dig=3)))[2]

legend('bottomright', legend = rp, bty = 'n', cex=1.5)







 
##CEREBELLUM
x <- log(Data_raw$enminuscereSA)
y <- log(Data_raw$cereSA)

# generate linear model
lm.mod <- lm(y ~ x)

# generate equidistant x values for lines
newx = seq(min(x),max(x),by = 0.05)

conf_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'confidence', level=0.95)
pred_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'prediction', level=0.95)



 plot(log(Data_raw$cereSA) ~ log(Data_raw$enminuscereSA), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order],  cex=2, ylab="Cerebellum from Endocast", xlab="Endocast Remainder", cex.main=3, cex.axis=1.8, cex.lab=1.8);
 

 #Here we make the  CI polygon. To make that appear behind the plot, I have to repeat the plot command
 polygon(c(CereEndo_gm_CI$CI.plot$X, rev (CereEndo_gm_CI$CI.plot$X)), c(CereEndo_gm_CI$CI.plot$Lower2.5, rev(CereEndo_gm_CI$CI.plot$Upper2.5)), col = "lightpink", border = NA )

polygon(c(newx, rev(newx)), c(pred_interval[,2], rev(pred_interval[,3])), col = grey (0.9), border = NA )
polygon(c(newx, rev(newx)), c(conf_interval[,2], rev(conf_interval[,3])), col = grey (0.5), border = NA )

abline(lm.mod, col="black", lwd=2);

 #I am here using the abline from the evomap code, but the pgls with brownian settings results in teh same line
abline (CereEndo_gm_CI$model[1,1], CereEndo_gm_CI$model[2,1], col="red", lwd=2, lty=5)

 
par(new=TRUE)

 plot(log(Data_raw$cereSA) ~ log(Data_raw$enminuscereSA), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order],  cex=2, ylab="Cerebellum from Endocast", xlab="Endocast Remainder", cex.main=3, cex.axis=1.8, cex.lab=1.8);


 
legend('topleft', legend = "(c) Log Surface Area (mm²)", cex = 2, bty = 'n')
model <- ((gls( log(cereSA) ~ log(enminuscereSA), correlation = corBrownian(1,consensus_tree_cere, form=~Tree_label_name), data=Phylo_Data_Cere)));
# 
# 
modsum = summary(model)

pgls.slope=coef(modsum)[2]
lm.slope=coef(lm.mod)[2]

rp = vector('expression',2)
 
rp[1] = substitute(expression(LM_Slope == MYVALUE), list(MYVALUE = format(lm.slope,dig=3)))[2]
rp[2] = substitute(expression(PGLS_Slope == MYVALUE), list(MYVALUE = format(pgls.slope,dig=3)))[2]

legend('bottomright', legend = rp, bty = 'n', cex=1.5)

 
#cerebellum brain
 x <- log(Phylo_Data_Cere$brminuscereVOL)
y <- log(Phylo_Data_Cere$cereVOL)

# generate linear model
lm.mod <- lm(y ~ x)

# generate equidistant x values for lines
newx = seq(min(x),max(x),by = 0.05)

conf_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'confidence', level=0.95)
pred_interval <- predict(lm.mod, newdata = data.frame(x=newx), interval = 'prediction', level=0.95)





plot(log(Data_raw$cereVOL) ~ log(Data_raw$brminuscereVOL), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order],  cex=2, ylab="Cerebellum from Brain", xlab="Brain Remainder", cex.main=3, cex.axis=1.8, cex.lab=1.8);

 #Here we make the  CI polygon. To make that appear behind the plot, I have to repeat the plot command
polygon(c(CereBrain_gm_CI$CI.plot$X, rev (CereBrain_gm_CI$CI.plot$X)), c(CereBrain_gm_CI$CI.plot$Lower2.5, rev(CereBrain_gm_CI$CI.plot$Upper2.5)), col = "lightpink", border = NA )

polygon(c(newx, rev(newx)), c(pred_interval[,2], rev(pred_interval[,3])), col = grey (0.9), border = NA )
polygon(c(newx, rev(newx)), c(conf_interval[,2], rev(conf_interval[,3])), col = grey (0.5), border = NA )

abline(lm.mod, col="black", lwd=2);

 #I am here using the abline from the evomap code, but the pgls with brownian settings results in teh same line
abline (CereBrain_gm_CI$model[1,1], CereBrain_gm_CI$model[2,1], col="red", lwd=2, lty=5)

 
par(new=TRUE)


plot(log(Data_raw$cereVOL) ~ log(Data_raw$brminuscereVOL), bg=colsOrderBG[Data_raw$order], col=colsOrder[Data_raw$order], pch=pchOrder[Data_raw$order],  cex=2, ylab="Cerebellum from Brain", xlab="Brain Remainder", cex.main=3, cex.axis=1.8, cex.lab=1.8);


legend('topleft', legend = "(d) Log Volume (mm³)", cex = 2, bty = 'n')
model <- ((gls( log(cereVOL) ~ log(brminuscereVOL), correlation = corBrownian(1,consensus_tree_cere, form=~Tree_label_name), data=Phylo_Data_Cere)));
# 
# 
modsum = summary(model)

pgls.slope=coef(modsum)[2]
lm.slope=coef(lm.mod)[2]

rp = vector('expression',2)
 
rp[1] = substitute(expression(LM_Slope == MYVALUE), list(MYVALUE = format(lm.slope,dig=3)))[2]
rp[2] = substitute(expression(PGLS_Slope == MYVALUE), list(MYVALUE = format(pgls.slope,dig=3)))[2]

legend('bottomright', legend = rp, bty = 'n', cex=1.5)

par(mar=c(5, 5, 3, 3),mfrow=c(2,1))

# Create a blank plot with no data and no box
plot(NA, xlim = c(0, 1), ylim = c(0, 1), type = "n", xlab = "", ylab = "", main = "", axes = FALSE)

legend("topleft", levels(as.factor(Data_raw$order)),  pt.bg=colsOrderBG, col=colsOrder, pch=pchOrder, cex=1, bty="n",xpd = TRUE, ncol=5 )



# Close the PDF device
dev.off()


```
